Repository repobee/repobee-sanitizer, pull requests merged in 2021-02, with the labels that each got.

#126 [docs] Include usage instructions in README
  README.md
Labels: documentation

#127 [feat] Add and improve operation descriptions
  repobee_sanitizer/sanitizer.py
Labels: documentation, enhancement

#130 [docs] fix shred marker in README
  README.md
Labels: documentation

#132 [misc] Set checkout fetch-depth to 2
  .github/workflows/python-app.yml
Labels: testing
